from .models import Level

__all__ = ["LEVELS", "BY_ID", "BY_NUMBER"]

LEVELS = [
    Level(
        name="2Twelve",
        number=1,
        internal_name="2twelve",
        internal_id=1,
        order_options=[["NACHO", "PRETZEL"]],
        solid_inputs=[["NACHO"], ["PRETZEL"]],
        other_inputs=[["CHEESE"]],
    ),
    Level(
        name="Original Hot Pocket Experience",
        number=2,
        internal_name="original-hot-pocket-experience",
        internal_id=2,
        order_options=[["POCKET"]],
        solid_inputs=[["POCKET"]],
        other_inputs=[],
    ),
    Level(
        name="Wine O'Clock",
        number=3,
        internal_name="wine-oclock",
        internal_id=8,
        order_options=[["RED", "WHITE"]],
        solid_inputs=[["CUP"]],
        other_inputs=[["RED", "WHITE"]],
    ),
    Level(
        name="Mumbai Chaat",
        number=4,
        internal_name="mumbai-chaat",
        internal_id=6,
        order_options=[["POORI", "PAPDI"]],
        solid_inputs=[["DOUGH"]],
        other_inputs=[["TOMATO", "MINT", "YOGURT"]],
    ),
    Level(
        name="Mr. Chilly",
        number=5,
        internal_name="mr.-chilly",
        internal_id=3,
        order_options=[["CHOCO", "VANILLA", "TWIST"], ["SMALL", "MEDIUM", "LARGE"]],
        solid_inputs=[["CONE"]],
        other_inputs=[["CHOCO", "VANILLA"]],
    ),
    Level(
        name="KAZAN",
        number=6,
        internal_name="kazan",
        internal_id=5,
        order_options=[["1 PC.", "3 PCS.", "6 PCS.", "10 PCS.", "15 PCS.", "21 PCS."]],
        solid_inputs=[["PELMENI"]],
        other_inputs=[],
    ),
    Level(
        name="Soda Trench",
        number=7,
        internal_name="soda-trench",
        internal_id=9,
        order_options=[["COKE", "DIET C.", "PEPSI", "DIET P."]],
        solid_inputs=[["CUP", "LID"]],
        other_inputs=[["COLA"]],
    ),
    Level(
        name="Rosie's Doughnuts",
        number=8,
        internal_name="rosies-doughnuts",
        internal_id=7,
        order_options=[["ONE", "SIX", "DOZEN"], ["PLAIN", "CHOCO", "BERRY"]],
        solid_inputs=[["DOUGH"]],
        other_inputs=[["CHOCO"], ["BERRY"], ["CANDY"]],
    ),
    Level(
        name="On the Fried Side",
        number=9,
        internal_name="on-the-fried-side",
        internal_id=4,
        order_options=[["WHOLE", "HALF", "CUTLET", "LEG"]],
        solid_inputs=[["CHICKEN"]],
        other_inputs=[["BREADING"]],
    ),
    Level(
        name="Sweet Heat BBQ",
        number=10,
        internal_name="sweet-heat-bbq",
        internal_id=14,
        order_options=[["ROAST", "RIBS"], ["200G", "400G", "600G"]],
        solid_inputs=[["ROAST", "RIBS"]],
        other_inputs=[],
    ),
    Level(
        name="The Walrus",
        number=11,
        internal_name="the-walrus",
        internal_id=20,
        order_options=[["WHISKY", "W. SOUR", "HIGHBALL", "COLA"]],
        solid_inputs=[["ICE"], ["CUP"]],
        other_inputs=[["VODKA", "WHISKY"], ["COLA", "LEMON"]],
    ),
    Level(
        name="Meat+3",
        number=12,
        internal_name="meat+3",
        internal_id=10,
        order_options=[["MAC"], ["SLAW"], ["GREENS"], ["BEANS"]],
        solid_inputs=[["MEAT"], ["BOWL"]],
        other_inputs=[["MAC"], ["SLAW"], ["GREENS"], ["BEANS"]],
    ),
    Level(
        name="Cafe Triste",
        number=13,
        internal_name="cafe-triste",
        internal_id=13,
        order_options=[["DU JOUR"]],
        solid_inputs=[["PAPER"], ["CUP"]],
        other_inputs=[["LEAVES"]],
    ),
    Level(
        name="The Commissary",
        number=14,
        internal_name="the-commissary",
        internal_id=15,
        order_options=[["MON.", "TUES.", "WED.", "THUR.", "FRI."]],
        solid_inputs=[
            ["PIZZA", "BURGER", "TENDER", "CORNDOC", "CURLY", "CRINKLE", "TOT"],
            ["PLAIN", "CHOCO"],
        ],
        other_inputs=[],
    ),
    Level(
        name="Da Wings",
        number=15,
        internal_name="da-wings",
        internal_id=11,
        order_options=[["3 PCS.", "6 PCS.", "9 PCS."]],
        solid_inputs=[["CHICKEN"]],
        other_inputs=[["SAUCE"]],
    ),
    Level(
        name="Breakside Grill",
        number=16,
        internal_name="breakside-grill",
        internal_id=18,
        order_options=[
            ["SINGLE", "DOUBLE", "TRIPLE"],
            ["CHEESE"],
            ["PICKLE"],
            ["TOMATO"],
        ],
        solid_inputs=[["MEAT"], ["BUN"], ["CHEESE", "PICKLE", "TOMATO"]],
        other_inputs=[],
    ),
    Level(
        name="Chaz Cheddar",
        number=17,
        internal_name="chaz-cheddar",
        internal_id=16,
        order_options=[["MEAT L."], ["MEAT R."], ["VEGGIE L."], ["VEGGIE R."]],
        solid_inputs=[["DOUGH"]],
        other_inputs=[["SAUCE"], ["CHEESE"], ["MEAT"], ["VEGGIE"]],
    ),
    Level(
        name="Half Caff Coffee",
        number=18,
        internal_name="half-caff-coffee",
        internal_id=17,
        order_options=[["ESPRE.", "DOPPIO", "LATTE", "CAPP.", "AMER."]],
        solid_inputs=[["CUP"]],
        other_inputs=[["MILK"], ["WATER"]],
    ),
    Level(
        name="Mildred's Nook",
        number=19,
        internal_name="mildreds-nook",
        internal_id=19,
        order_options=[["SOFT", "HARD"]],
        solid_inputs=[
            ["EGG"],
            ["BACON", "BANGER"],
            ["TOMATO", "FUNGUS", "BLACK"],
            ["BREAD"],
        ],
        other_inputs=[["BEANS"]],
    ),
    Level(
        name="Belly's",
        number=20,
        internal_name="bellys",
        internal_id=12,
        order_options=[
            ["PLAIN", "CHEESE"],
            ["ORANGE", "PURPLE"],
            ["POTATO", "ONION"],
        ],
        solid_inputs=[
            ["MEAT", "POTATO", "ONION"],
            ["BUN", "CHEESE"],
            ["CUP", "LID"],
        ],
        other_inputs=[["ORANGE", "PURPLE"]],
    ),
    Level(
        name="Sushi Yeah!",
        number=21,
        internal_name="sushi-yeah!",
        internal_id=21,
        order_options=[
            ["T. MAKI", "S. MAKI", "T. NIGIRI", "S. NIGIRI", "SASHIMI", "SOUP"]
        ],
        solid_inputs=[["NORI", "RICE"], ["TUNA", "SALMON"], ["PLATE", "BOWL"]],
        other_inputs=[["SOUP"]],
    ),
]

BY_NUMBER = {level.number: level for level in LEVELS}
BY_ID = {level.internal_id: level for level in LEVELS}
